import type { ProjectYaml } from '../yaml.js';
import { stackWithLanguage } from '../wizard-flow.js';

/**
 * Shared git pre-commit hook. Runtimes without native blocking hooks
 * (OpenCode, Codex) rely on this executable fallback so branch guard and
 * debug detection still run automatically. Install it with:
 *   git config core.hooksPath .githooks
 *
 * POSIX sh, zero Python, never blocks on documentation-only edits.
 */
export function generateSharedPreCommitHook(): string {
  return `#!/bin/sh
# forge — shared git pre-commit hook (fallback for runtimes without native hooks)
# Generated by forge v2. Enable with: git config core.hooksPath .githooks
#
# Guardrails:
#   1. Branch guard   — block commits straight to main/master
#   2. Debug detection — block leftover console.log/debugger/print/dd/var_dump
set -eu

branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")
staged=$(git diff --cached --name-only --diff-filter=ACM 2>/dev/null || echo "")

# Only documentation/config edits are exempt from the branch guard.
code_staged=$(printf '%s\\n' "$staged" | grep -vE '\\.(md|ya?ml|json|txt)$' || true)

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  if [ -n "$code_staged" ]; then
    echo "forge: BLOQUEADO — estás commiteando código en '$branch'." >&2
    echo "  Creá una rama de feature antes de commitear:" >&2
    echo "    git checkout -b feat/descripcion" >&2
    echo "  (solo *.md / *.yaml / *.json / *.txt pueden commitearse en main)" >&2
    exit 1
  fi
fi

# Debug detection on staged code files.
debug_hits=""
for f in $code_staged; do
  [ -f "$f" ] || continue
  hit=$(grep -nE '(console\\.log\\(|debugger;|binding\\.pry|var_dump\\(|[^a-zA-Z_]dd\\()' "$f" 2>/dev/null || true)
  if [ -n "$hit" ]; then
    debug_hits="$debug_hits\\n$f:\\n$hit"
  fi
done

if [ -n "$debug_hits" ]; then
  echo "forge: BLOQUEADO — sentencias de debug en archivos staged:" >&2
  printf '%b\\n' "$debug_hits" >&2
  echo "  Eliminalas (o usá 'git commit --no-verify' bajo tu responsabilidad)." >&2
  exit 1
fi

exit 0
`;
}

const AGENT_DESCRIPTIONS: Record<string, string> = {
  'orchestrator':         'Coordina agentes y descompone tareas complejas',
  'backend-engineer':     'API, base de datos, lógica de negocio',
  'api-engineer':         'Endpoints REST, middleware, validaciones',
  'frontend-engineer':    'UI, componentes, integración con API',
  'admin-engineer':       'Interfaces de administración y dashboards',
  'mobile-engineer':      'Pantallas móviles, navegación, estado',
  'fullstack-engineer':   'Features full-stack de extremo a extremo',
  'test-engineer':        'Tests unitarios, integración y E2E',
  'docs-writer':          'Specs, ADRs, READMEs, documentación',
  'compliance-reviewer':  'Revisión de PRs con PII y compliance regulatorio',
  'security-auditor':     'Auditoría de vulnerabilidades y dependencias',
  'migration-specialist': 'Migraciones de versión de framework',
  'wp-engineer':          'Temas WordPress, FSE, Gutenberg',
  'scanner-engineer':     'Scraping, crawling, extracción de datos',
};

function guardrailSection(): string {
  return `## Guardrails de seguridad

OpenCode no tiene hooks PreToolUse/Stop nativos. Branch guard y detección de
debug se aplican de forma **automática** mediante el git hook compartido en
\`.githooks/pre-commit\` (generado por forge). Activalo una vez con:

\`\`\`
git config core.hooksPath .githooks
\`\`\`

Las siguientes reglas aplican a TODOS los agentes sin excepción (el git hook
refuerza branch guard y debug detection en cada \`git commit\`):

### Branch guard
- Verificar siempre la rama antes de hacer cambios: \`git branch --show-current\`
- **NUNCA** hacer push directo a \`main\` o \`master\`
- Si estás en main/master, crear una rama antes de cualquier edición: \`git checkout -b fix/descripcion\`

### Debug detection
- No commitear \`console.log\`, \`print()\`, \`dd()\`, \`var_dump()\`, \`debugger\`, \`binding.pry\`
- Si los encuentras en código existente, eliminarlos antes de commitear

### Production safety
- Nunca ejecutar comandos destructivos en producción sin confirmación explícita
- Comandos bloqueados en producción: \`--force-reset\`, \`DROP TABLE\`, \`TRUNCATE\`, \`rm -rf /\`, \`git push --force\`

### Secrets
- Nunca hardcodear tokens, passwords o API keys en archivos que van a git
- Usar variables de entorno o secret managers
`;
}

function commandsSection(deployProvider: string): string {
  return `## Flujo de trabajo (SDD)

OpenCode no tiene slash commands ni agent teams paralelos: aplicá este flujo
manualmente, ejecutando un agente a la vez.

| Paso | Qué hacer |
|------|-----------|
| **Plan** | Creá o revisá la spec en \`docs/specs/\` antes de tocar código |
| **Work** | Implementá solo lo que la spec aprueba; tests junto con el código |
| **Review** | Revisá el diff: ¿cumple la spec?, ¿secrets/debug?, ¿pasa typecheck/lint? |
| **Ship** | Deploy a ${deployProvider} solo con tests + typecheck en verde y smoke tests OK |

> **Nota OpenCode**: ejecución serial — un agente a la vez, sin teams paralelos.
`;
}

/**
 * Nested AGENTS.md for monorepo scopes. The AGENTS.md standard resolves
 * precedence by proximity: the file closest to the code wins. When
 * `agents.scope` maps agents to subdirectories, forge emits one AGENTS.md
 * per scoped directory so the nested precedence is materialized, not implied.
 */
export function generateNestedAgentsMd(config: ProjectYaml, dir: string, scoped: string[]): string {
  const name = config.project?.name ?? 'Mi Proyecto';
  const rows = scoped
    .map(a => `| \`${a}\` | ${AGENT_DESCRIPTIONS[a] ?? 'Agente especializado'} |`)
    .join('\n');

  return `# AGENTS.md — ${name} (\`${dir}/\`)

> Generado por forge v2. Actualizar project.yaml para cambiar la configuración.
> Precedencia del estándar AGENTS.md: este archivo aplica a todo lo que está
> bajo \`${dir}/\` y tiene prioridad sobre el \`AGENTS.md\` de la raíz.

## Agentes con scope en \`${dir}/\`

| Agente | Descripción |
|--------|-------------|
${rows}

Usar estos agentes para el código bajo \`${dir}/\`. Las reglas generales del
proyecto (workflow SDD y guardrails) están en el \`AGENTS.md\` de la raíz y
siguen aplicando salvo indicación contraria en este archivo.
`;
}

/**
 * Surfaces of the nested AGENTS.md files derived from `agents.scope`
 * (monorepo precedence). Scopes that resolve to the repo root ('/', '', '.')
 * are covered by the root AGENTS.md and produce no nested file.
 */
export function nestedAgentsSurfaces(config: ProjectYaml): Array<{ path: string; content: string }> {
  const scope = config.agents?.scope ?? {};
  const byDir = new Map<string, string[]>();
  for (const [agent, raw] of Object.entries(scope)) {
    // Normalizar separadores Windows ANTES del guard: sin esto, un scope
    // '..\\..\\fuera' pasa el split('/') y path.join escribiría fuera de la
    // raíz del proyecto en Windows.
    const normalized = String(raw ?? '').trim().replace(/\\/g, '/');
    // Rechazar drive letters (C:/x, C:x) — rutas absolutas de Windows.
    if (/^[a-zA-Z]:/.test(normalized)) continue;
    const dir = normalized
      .replace(/^\.\//, '')
      .replace(/^\/+/, '')
      .replace(/\/+$/, '');
    if (!dir || dir === '.' || dir.split('/').includes('..')) continue;
    byDir.set(dir, [...(byDir.get(dir) ?? []), agent]);
  }
  return [...byDir.keys()].sort().map(dir => ({
    path: `${dir}/AGENTS.md`,
    content: generateNestedAgentsMd(config, dir, byDir.get(dir)!),
  }));
}

export function generateAgentsMd(config: ProjectYaml): string {
  const proj = config.project;
  const stack = config.stack ?? {};
  const agents = config.agents ?? {};
  const compliance = config.compliance ?? {};

  const name = proj.name ?? 'Mi Proyecto';
  const language = proj.language ?? 'typescript';
  const active = agents.active ?? [];
  const complianceAgents = agents.compliance ?? [];
  const profiles = agents.profiles ?? [];
  const allAgents = [...active, ...complianceAgents];

  const agentRows = allAgents
    .map(a => `| \`${a}\` | ${AGENT_DESCRIPTIONS[a] ?? 'Agente especializado'} |`)
    .join('\n');

  const complianceSection = compliance.frameworks && compliance.frameworks.length > 0
    ? `\n## Compliance\n\nMarcos activos: ${compliance.frameworks.map(f => f.toUpperCase()).join(', ')}\n`
    : '';

  return `# AGENTS.md — ${name}

> Generado por forge v2. Actualizar project.yaml para cambiar la configuración.

## Proyecto

- **Nombre**: ${name}
- **Lenguaje**: ${language}
- **Backend**: ${stackWithLanguage(stack.backend, stack.backend_language)}
- **Frontend**: ${stackWithLanguage(stack.frontend, stack.frontend_language)}${stack.mobile ? `\n- **Mobile**: ${stackWithLanguage(stack.mobile, stack.mobile_language)}` : ''}
- **Base de datos**: ${stack.database ?? 'N/A'}
- **Profiles activos**: ${profiles.join(', ') || '—'}

## Agentes del equipo

| Agente | Descripción |
|--------|-------------|
${agentRows || '| — | Sin agentes declarados en project.yaml |'}

> Invocar el agente especializado para cada tarea. Usar orchestrator solo para tareas multi-agente.

${commandsSection(config.deploy?.provider ?? 'tu plataforma de deploy')}
${guardrailSection()}${complianceSection}`;
}
