// SPEC-083 P6 — instalador de approvals (mitad forge de SPEC-081).
//
// `forge generate --runtime claude-code` con approvals.enabled: true instala
// .claude/hooks/pre-approval-gate.js y registra la entrada PreToolUse en
// .claude/settings.json; con false/ausente no instala y retira el registro.
// Supervivencia: --force conserva hook y registro sin duplicar; un hook
// editado a mano (sin marcador forge) jamás se pisa.
//
// Requiere build previo (npm run build:all), como spec-083-conformance.test.mjs.
//
//     node --test test/approvals-install.test.mjs

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  existsSync, mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CLI = join(__dirname, '..', 'dist', 'cli.js');

const HOOK_REL = join('.claude', 'hooks', 'pre-approval-gate.js');
const SETTINGS_REL = join('.claude', 'settings.json');
const MATCHER = 'Bash|Edit|Write|ExitPlanMode|AskUserQuestion';

before(() => {
  assert.ok(existsSync(CLI), 'dist/cli.js no existe — correr npm run build:all primero');
});

function makeTmpDir(t) {
  const dir = mkdtempSync(join(tmpdir(), 'forge-083p6-'));
  t.after(() => rmSync(dir, { recursive: true, force: true, maxRetries: 5 }));
  return dir;
}

function writeYaml(dir, { approvals } = {}) {
  let yaml = `project:
  name: "demo-approvals"
  mode: standard
  language: typescript
`;
  if (approvals !== undefined) {
    yaml += `approvals:
  enabled: ${approvals}
`;
  }
  writeFileSync(join(dir, 'project.yaml'), yaml);
}

function runGenerate(dir, extra = []) {
  return runForge(dir, ['generate', '--runtime', 'claude-code', ...extra]);
}

function runForge(dir, args) {
  const res = spawnSync(process.execPath, [CLI, ...args], {
    cwd: dir,
    encoding: 'utf-8',
    env: { ...process.env, FORGE_HOME: '', FORGE_NO_BUN: '1', FORGE_NO_DASHBOARD: '1' },
  });
  return { status: res.status ?? 1, stdout: res.stdout ?? '', stderr: res.stderr ?? '' };
}

/** Entradas PreToolUse cuyo command referencia el approval gate. */
function gateEntries(dir) {
  const path = join(dir, SETTINGS_REL);
  if (!existsSync(path)) return [];
  const settings = JSON.parse(readFileSync(path, 'utf-8'));
  const pre = settings.hooks?.PreToolUse ?? [];
  return pre.filter(e => (e.hooks ?? []).some(h => String(h.command ?? '').includes('pre-approval-gate.js')));
}

/** Shape que valida la suite de conformidad P1 sobre settings.json. */
function assertP1Shape(dir) {
  const settings = JSON.parse(readFileSync(join(dir, SETTINGS_REL), 'utf-8'));
  assert.ok(settings.hooks && typeof settings.hooks === 'object', 'hooks ausente');
  for (const [event, entries] of Object.entries(settings.hooks)) {
    assert.ok(Array.isArray(entries), `hooks.${event} debe ser lista`);
    for (const entry of entries) {
      assert.ok(Array.isArray(entry.hooks), `hooks.${event}[].hooks debe ser lista`);
      for (const h of entry.hooks) {
        assert.equal(h.type, 'command', `hooks.${event}: type debe ser 'command'`);
        assert.equal(typeof h.command, 'string', `hooks.${event}: command debe ser string`);
      }
    }
  }
}

describe('SPEC-083 P6 — approvals.enabled: true instala y registra', () => {
  test('generate instala el hook, lo registra y el shape pasa la conformidad P1', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir, { approvals: true });
    const res = runGenerate(dir);
    assert.equal(res.status, 0, res.stderr || res.stdout);

    // Hook instalado, idéntico al bundle (JS puro, con marcador forge).
    assert.ok(existsSync(join(dir, HOOK_REL)), 'hook no instalado');
    const hook = readFileSync(join(dir, HOOK_REL), 'utf-8');
    assert.match(hook, /Generated by forge/);
    assert.ok(!/require\(['"](?!node:)[a-z@][^'"]*['"]\)/.test(hook.replace(/require\(['"](fs|path|os|http)['"]\)/g, '')), 'el hook no debe requerir paquetes externos');

    // Registro en settings.json con el matcher del contrato.
    const entries = gateEntries(dir);
    assert.equal(entries.length, 1, 'debe haber exactamente una entrada del gate');
    assert.equal(entries[0].matcher, MATCHER);
    assert.equal(entries[0].hooks[0].command, 'node .claude/hooks/pre-approval-gate.js');
    assertP1Shape(dir);
  });

  test('registro idempotente: settings.json existente conserva sus keys y no duplica', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir, { approvals: true });
    mkdirSync(join(dir, '.claude'), { recursive: true });
    writeFileSync(join(dir, SETTINGS_REL), JSON.stringify({
      env: { FOO: 'bar' },
      permissions: { allow: ['Bash(git *)'] },
      hooks: { PreToolUse: [{ matcher: '.*', hooks: [{ type: 'command', command: 'node .claude/hooks/pre-edit-check.js' }] }] },
    }, null, 2));

    assert.equal(runGenerate(dir).status, 0);
    assert.equal(runGenerate(dir, ['--force']).status, 0);

    const settings = JSON.parse(readFileSync(join(dir, SETTINGS_REL), 'utf-8'));
    assert.deepEqual(settings.env, { FOO: 'bar' }, 'keys externas preservadas');
    assert.deepEqual(settings.permissions, { allow: ['Bash(git *)'] });
    assert.equal(settings.hooks.PreToolUse.length, 2, 'pre-edit-check + gate, sin duplicar');
    assert.equal(gateEntries(dir).length, 1);
  });
});

describe('SPEC-083 P6 — approvals false/ausente no instala y retira el registro', () => {
  test('sin la clave approvals: no instala hook ni crea settings.json', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir);
    const res = runGenerate(dir);
    assert.equal(res.status, 0, res.stderr || res.stdout);
    assert.ok(!existsSync(join(dir, HOOK_REL)), 'no debe instalar el hook');
    assert.ok(!existsSync(join(dir, SETTINGS_REL)), 'no debe crear settings.json');
  });

  test('approvals.enabled: false tras true → retira el registro (el .js queda huérfano inocuo)', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir, { approvals: true });
    assert.equal(runGenerate(dir).status, 0);
    assert.equal(gateEntries(dir).length, 1);

    writeYaml(dir, { approvals: false });
    assert.equal(runGenerate(dir).status, 0);
    assert.equal(gateEntries(dir).length, 0, 'el registro debe retirarse');
    assert.ok(existsSync(join(dir, HOOK_REL)), 'el archivo del hook queda (huérfano documentado)');
    assertP1Shape(dir);
  });
});

describe('SPEC-083 P6 — supervivencia a regeneraciones', () => {
  test('generate --force conserva hook y registro', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir, { approvals: true });
    assert.equal(runGenerate(dir).status, 0);
    assert.equal(runGenerate(dir, ['--force']).status, 0);
    assert.equal(runGenerate(dir, ['--force']).status, 0);

    assert.ok(existsSync(join(dir, HOOK_REL)));
    assert.match(readFileSync(join(dir, HOOK_REL), 'utf-8'), /Generated by forge/);
    assert.equal(gateEntries(dir).length, 1, 'el registro sobrevive sin duplicarse');
  });

  test('un pre-approval-gate.js manual (sin marcador forge) no se pisa ni con --force', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir, { approvals: true });
    mkdirSync(join(dir, '.claude', 'hooks'), { recursive: true });
    const manual = '#!/usr/bin/env node\n// hook propio del proyecto, escrito a mano\nprocess.exit(0);\n';
    writeFileSync(join(dir, HOOK_REL), manual);

    assert.equal(runGenerate(dir, ['--force']).status, 0);
    assert.equal(readFileSync(join(dir, HOOK_REL), 'utf-8'), manual, 'el archivo manual no debe pisarse');
    assert.equal(gateEntries(dir).length, 1, 'el registro igual se hace (el hook manual sigue siendo el gate)');
  });

  test('forge init --force conserva el registro del gate (mergeSettings reemplaza hooks)', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir, { approvals: true });
    assert.equal(runGenerate(dir).status, 0);
    assert.equal(gateEntries(dir).length, 1);

    // Regresión: init --force sin propagar approvals.enabled borraba la
    // entrada del gate de settings.json hasta el próximo forge generate.
    const res = runForge(dir, ['init', '--force']);
    assert.equal(res.status, 0, res.stderr || res.stdout);
    assert.equal(gateEntries(dir).length, 1, 'init --force no debe retirar el registro del gate');
    assert.ok(existsSync(join(dir, HOOK_REL)), 'init también instala el hook (registro sin instalación, jamás)');
    assertP1Shape(dir);
  });

  test('forge init con approvals.enabled: true instala hook + registro sin pasar por generate', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir, { approvals: true });
    const res = runForge(dir, ['init', '--force']);
    assert.equal(res.status, 0, res.stderr || res.stdout);
    assert.ok(existsSync(join(dir, HOOK_REL)), 'hook no instalado por init');
    assert.match(readFileSync(join(dir, HOOK_REL), 'utf-8'), /Generated by forge/);
    assert.equal(gateEntries(dir).length, 1);
    assert.equal(gateEntries(dir)[0].matcher, MATCHER);
  });

  test('forge init sin approvals: no registra el gate', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir);
    assert.equal(runForge(dir, ['init', '--force']).status, 0);
    assert.equal(gateEntries(dir).length, 0);
    assert.ok(!existsSync(join(dir, HOOK_REL)), 'sin approvals no se copia el hook');
  });

  test('forge adopt --yes con project.yaml preexistente (approvals: true) instala hook + registro', (t) => {
    const dir = makeTmpDir(t);
    writeFileSync(join(dir, 'package.json'), JSON.stringify({ name: 'demo-adopt', version: '1.0.0' }));
    writeYaml(dir, { approvals: true }); // preexistente: adopt lo preserva sin --force

    // Regresión: adopt registraba el gate en settings.json pero installHooks
    // no copiaba pre-approval-gate.js → hook fantasma en cada tool call.
    const res = runForge(dir, ['adopt', '--yes', '--no-wiki', dir]);
    assert.equal(res.status, 0, res.stderr || res.stdout);
    assert.ok(existsSync(join(dir, HOOK_REL)), 'adopt debe instalar el hook que registra');
    assert.equal(gateEntries(dir).length, 1);
    assert.equal(gateEntries(dir)[0].matcher, MATCHER);
    assertP1Shape(dir);
  });

  test('settings.json con JSON inválido: generate no lo pisa y no falla', (t) => {
    const dir = makeTmpDir(t);
    writeYaml(dir, { approvals: true });
    mkdirSync(join(dir, '.claude'), { recursive: true });
    writeFileSync(join(dir, SETTINGS_REL), '{ roto');

    const res = runGenerate(dir);
    assert.equal(res.status, 0, res.stderr || res.stdout);
    assert.equal(readFileSync(join(dir, SETTINGS_REL), 'utf-8'), '{ roto', 'no debe pisar un settings.json inválido');
  });
});
